# Very simple workflow to deploy the *latest* published container image with the 'latest' tag. 
# This does not post updated module descriptors to okapi, update permissions or enable 
# new versions of a module with the tenant.  If that is needed,  it should be done manually
# via the Okapi API. 

name: k8s-deploy-latest

env:
  K8S_NAMESPACE: 'snapshot-dev'
  K8S_DEPLOYMENT: 'mod-circulation-dev'

on:
  workflow_dispatch

jobs: 
  k8s-deploy-latest:

    runs-on: ubuntu-latest
    steps: 
      - name: Deploy latest to K8s
        uses: actions-hub/kubectl@v1.29.3
        env: 
          KUBE_CONFIG: ${{ secrets.SNAPSHOT_DEV_SA_KUBECONFIG }}
        with:
          args:
            -n ${{ env.K8S_NAMESPACE }} rollout restart deployment ${{ env.K8S_DEPLOYMENT }}
        
